services:
  db:
    image: postgres:16-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/go-vend-event
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/go_vend_event_development
    ports:
      - "3000:3000"
    depends_on:
      - db
